### ISSUE TITLE
Higher scale option (more than 100%)

### ISSUE THREAD

**Issue by 1upCAD** [FiniteSingularity/obs-advanced-masks#3]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Scale/Position Properties: Scale
It would be nice to have to option to go higher than 100%. Maybe up to 200%?

**Describe alternatives you've considered**
N/A

**Additional context**
For example, if you wanted to "zoom", such as a face closeup, you can't do it beyond 100% scale. Having the option to go up to 200% would open up another possibility.

**Comment by FiniteSingularity** [comment]
That’s in the pipeline.  Need to figure out how to do a quality upscale.

**Comment by FiniteSingularity** [comment]
Added with #4
