### ISSUE TITLE
[BUG] - Scale settings are not saved on exit

### ISSUE THREAD

**Issue by 1upCAD** [FiniteSingularity/obs-advanced-masks#32]
**Describe the bug**
Setting scale to less than 100% does not save on exit, reverts back to 100% on next load.

**To Reproduce**
Set shape to rectangle, set properties to your liking and then set the scale setting to 30% for example. Close OBS, wait a few seconds, then reload. The source should be back to 100% in scale.

**Expected behavior**
Scale setting should remain at what it was set on exit.

**Screenshots**

Before close (source filter set at 30% scale):
![image](https://github.com/FiniteSingularity/obs-advanced-masks/assets/76631475/d6214abe-f23e-495b-b52f-c148d5295a17)

After close and reload (source filter reverts back to 100% scale):
![image](https://github.com/FiniteSingularity/obs-advanced-masks/assets/76631475/0182ba8e-c4c1-48a9-9773-9648d98e845b)

**Environment**
 - OS/Version: [e.g. Windows 10]
 - OBS Version: [e.g. 29.1.3]
 - Advanced Mask Version: Pre-Release 0.0.6a

**Comment by FiniteSingularity** [comment]
Hi @1upCAD, thank you for the bug report.

I am not able to reproduce this (seems to behave as expected on my end), but this may be due to some bugfixes/updates that were included in the latest release: https://github.com/FiniteSingularity/obs-advanced-masks/releases/tag/v0.0.7a 

Please download 0.0.7a, and let me know if it fixes the issue.

**Comment by 1upCAD** [comment]
I updated to the latest version and the issue appears to still be there.

Here are my settings on a scene that includes just a camera.

Before:
![image](https://github.com/FiniteSingularity/obs-advanced-masks/assets/76631475/d5348b83-0937-4474-b4c0-931db7bd2f01)

After reload:
![image](https://github.com/FiniteSingularity/obs-advanced-masks/assets/76631475/2bf568cc-13b1-4961-8343-c8c2d5d92c4b)

**Comment by FiniteSingularity** [comment]
Very interesting.  I'm wondering if this has something to do with some early changes in variable names (I think you've been using the plugin for a few versions now?).  Have you tried deleting that one filter, and re-building it. I'll try again to reproduce it tomorrow.

**Comment by FiniteSingularity** [comment]
It does sound like a plugin issue.  So that I am trying to reproduce exactly what you've got, can you confirm:
You've got a scene, and that scene has a single camera source.  The filter is being applied to that camera source?

**Comment by 1upCAD** [comment]
I have a source with a single camera source, but the filter is applied to the scene, not the source. That scene is then added in other scenes.

**Comment by FiniteSingularity** [comment]
Thank you for the details.  I'll try to replicate the issue today.
