### ISSUE TITLE
[BUG] - Filter showing blank source.

### ISSUE THREAD

**Issue by sebelk** [FiniteSingularity/obs-advanced-masks#54]
**Describe the bug**
Filter make the source all black

**To Reproduce**

1.     Select the source you want to apply the shape mask to.
3.     Go to the Filters section for that source and click the + icon to add a new filter.
4.     Choose "Advanced Masks" from the filter list.
4.  See error

**Expected behavior**
It should apply the mask, for example a shape....

**Screenshots**
![imagen](https://github.com/FiniteSingularity/obs-advanced-masks/assets/4109256/09029b55-a057-4c00-a919-2c1917252dc3)

**Environment**
 - OS/Version: Fedora 39
 - OBS Version: 30.0.0

**GPU**
 - GPU make/model 00:02.0 VGA compatible controller: Intel Corporation WhiskeyLake-U GT2 [UHD Graphics 620] (rev 02) (prog-if 00 [VGA controller])

I compiled from sources and copy the files by hand to /usr subdirectories...

**Comment by mxdmedia** [comment]
Hi @sebelk,

I'm sorry you're having an issue with the plug-in.  I suspect that something is not loading in correctly.

Can you please run OBS (restart it if it is already running) then go to `Help --> Log Files --> Upload Current Log File` and paste the link it gives you here?  Alternatively, you can do `Help --> Log Files --> Show Log Files` and attach the current log file to this issue?  This will help me to determine why things aren't loading properly.

**Comment by FiniteSingularity** [comment]
Hi @sebelk,

I'm sorry you're having an issue with the plug-in.  I suspect that something is not loading in correctly.

Can you please run OBS (restart it if it is already running) then go to `Help --> Log Files --> Upload Current Log File` and paste the link it gives you here?  Alternatively, you can do `Help --> Log Files --> Show Log Files` and attach the current log file to this issue?  This will help me to determine why things aren't loading properly.

**Comment by sebelk** [comment]
Hi @FiniteSingularity 

My log file  is at https://obsproject.com/logs/Oq6KkDhnd72Qot42

Thanks in advance!!

**Comment by FiniteSingularity** [comment]
Oops! I just noticed that I copy/pasted the log output from composite blur, and forgot to change the tag, so it is actually the effect file loading of Advanced Mask that is happening.

When OBS reports:
```
Unable to load .effect file.  Errors: (None)
```

It usually means it cant find, or doesnt have permissions to open the .effect files.  When you did your install, where did you put the data files (as opposed to the library files)?

**Comment by sebelk** [comment]
@FiniteSingularity Great!

Because of your answer I did:

sudo mv  /usr/data/obs-plugins/obs-advanced-masks/shaders/  /usr/share/obs/obs-plugins/obs-advanced-masks/

and now it works!

**Comment by FiniteSingularity** [comment]
Fantastic! I'm glad it is working for you.
