### ISSUE TITLE
[BUG] - Unclear how to install

### ISSUE THREAD

**Issue by mixmix** [FiniteSingularity/obs-advanced-masks#57]
I'm not really sure how to use this repo - I'd love to use the nice shape mask ... but if I follow your guide there's not "advanced" filter.
I assume I have to install this but not clear what commands I should be running... `make` ? Is this made for a particular OS with assumptions of where files are installed?

**Comment by FiniteSingularity** [comment]
Hi @mixmix-

I'm sorry you are having issues with getting Advanced Masks up and running. I need to work on documentation for how to install. I assume that you are not wanting to do development work on the plugin, and just want to run it?  If so, there are 2 ways to install:

1. Probably the easiest is to go over on the OBS plugin page for Advanced Masks: https://obsproject.com/forum/resources/advanced-masks.1856/ .  There is a "Download" button in the upper right of the page.  Click there and you will have downloads of pre-built binaries/installers for different platforms/operating systems.
2. There are also pre-built binaries here.  From the front page of the plugin, click "Releases" in the right column.  Then click on the latest release, and under "Assets" find your platform/installer.  A link to the latest is: https://github.com/FiniteSingularity/obs-advanced-masks/releases/latest

Here is a good video on how to actually install what you download: https://youtu.be/F3rRn_VPp90?si=R5oaIxnL8vxl3d83&t=194

Please let me know if you have any more questions.

**Comment by mixmix** [comment]
Thank you! Those links are a big help
