### ISSUE TITLE
Applying Advanced mask to a color source breaks the gradient

### ISSUE THREAD

**Issue by DizzyBHigh** [FiniteSingularity/obs-advanced-masks#59]
**Describe the bug**
Applying the advanced mask to a colour source with a gradient applied removes the gradient or replaces it with solid colours
It does not seem to matter whether the mask is applied directly to the colour source or if the colour source is nested in scene.

**To Reproduce**
1. Create a colour source with a gradient
2. Apply the Advanced mask to the gradient
3. The gradient is removed and replaced with blocks of colour

**Expected behavior**
Expect the colour source to maintain its gradient and other settings

**Screenshots**
Gradient with mask disabled
![image](https://github.com/user-attachments/assets/6d567a89-0e52-4cb9-befc-8027c627c38c)
Gradient with mask Enabled
![image](https://github.com/user-attachments/assets/8913c26a-bbad-420c-8ed0-64f5758fbd3d)

**Environment**
 - OS/Version:  Windows 11
 - OBS Version: 30,12 64 bit
 - Advanced Masks Plugin Version: 1.1.0
 - Mask Type: Any Shape

**GPU**
 Nvidia RTX 4070 Ti Super
 - GPU VRAM 16GB

**Additional context**

**Comment by DizzyBHigh** [comment]
Apologies for submitting this, the zoom function seems to fix the gradient, I hadn't realised this is what the zoom function did!

**Comment by DizzyBHigh** [comment]
Think its ok to close this

**Comment by FiniteSingularity** [comment]
Glad you got it figured out.  Enjoy the plugin.
