### ISSUE TITLE
[BUG] - locale translation related bugs

### ISSUE THREAD

**Issue by ZRdRy** [FiniteSingularity/obs-advanced-masks#61]
AdvancedMasks=“Advanced Mask” doesn't work when making translations, and after translating “Advanced Mask” to another language, the OBS filter still shows the English Advanced Mask. It doesn't matter much, though....

**Comment by ZRdRy** [comment]
> Hi there.
> 
> First, I noticed the PRs you've submitted for ZN-ch translations on this and my other plugins. Thank you very much for taking the time to translate, and I'll merge them in shortly.
> 
> Regarding the filter menu item translation, this is actually the intended behavior. In early versions of Composite Blur (my first plugin), I was translating the filter name. However I was receiving a significant number of support requests of folks claiming the install would not work. It turns out, that since the documentation was telling folks to look for "Composite Blur" in their filter menu, they were missing the translated version. Rather than having to document each languages translation in terms of what to look for, I decided to leave the filter name in English to match the docs.

So cool, maybe it's the right thing to do to avoid some trouble.

**Comment by FiniteSingularity** [comment]
I'll go ahead and close this issue, but feel free to re-open if you have any ideas on how to address the confusion that I've seen with users.
