### ISSUE TITLE
[PERMISSION REQUEST] Flathub submission 

### ISSUE THREAD

**Issue by Andresdiaz16** [FiniteSingularity/obs-advanced-masks#64]
Hi Mark, first of all I'm sorry to open an issue for this, I didn't know where else to contact you,  I really love this plugin and recently I made the change to Linux so I tried installing it but since I was using the flatpak version of OBS the plugin didn't work and I saw you didn't have a flatpak build for it so I created one that I'm hoping I can submit to flathub this of course only if you allow it. 

The reason behind using flatpak instead of getting obs thru my package manager is because obs removes some of it's features (eg. custom dock and browser dock) when being installed like that and the flatpak version doesn't have this issue. That's also why I think a flatpak version is necessary.

Here are the changes I plan to submit to flathub let me know what you think:  [Advanced Masks Submission](https://github.com/Andresdiaz16/flathub/tree/Advanced-Masks-Plugin)

Best regards, 
Andres

**Comment by FiniteSingularity** [comment]
No worries.. this is a great place to open this issue.

Feel free to add a flat pack submission- it'll be a great way for folks to get access to the plugin on Linux.  I currently have a bit of a piecemeal solution where folks have created flatpacks for my other plugins.  I'd like to work on getting it all automated/part of the build process of the plugin, but in the meantime, welcome the work you're proposing.

**Comment by Andresdiaz16** [comment]
Thank you, I'll be closing this out then and making the submission appreciate it.
